# https://taskfile.dev

version: '3'

vars:
  BIN: wrss

dotenv: ['.env']

tasks:
  build:
    cmds:
      - go build -o bin/{{.BIN}}
  run:
    deps: [build]
    cmds:
      - bin/{{.BIN}}
    silent: true
  env:
    deps: [build]
    cmds:
      - bin/{{.BIN}} -env
    silent: true
  deps:
    cmds:
      - go mod tidy
      - go mod vendor
